### ISSUE TITLE
Having issues updating to 0.7.0 via Carthage

### ISSUE THREAD

**Issue by jianyaoang** [gilesvangruisen/Swift-YouTube-Player#200]
Thanks for the latest release 0.7.0

I tried installing it via Carthage, but am having issue:

```
*** Skipped building Swift-YouTube-Player due to the error:
Dependency "Swift-YouTube-Player" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/gilesvangruisen/Swift-YouTube-Player/issues/new
```

Cartfile:
github "gilesvangruisen/Swift-YouTube-Player"

**Comment by gilesvangruisen** [comment]
Hey @jianyaoang really sorry for the delay! Some things got shuffled around in the 0.7.0 and it looks like I mistakenly removed the `xcshareddata` which broke Carthage. I just pushed a v0.7.1, which should hopefully fix your issue. 

Closing for now but please reopen and ping me if this continues to be a problem. Thanks!

**Comment by jianyaoang** [comment]
@gilesvangruisen Thanks for the 0.7.1 release. However, I am still facing the same issue. When i ran `carthage update --platform iOS`

```
*** Skipped building Swift-YouTube-Player due to the error:
Dependency "Swift-YouTube-Player" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/gilesvangruisen/Swift-YouTube-Player/issues/new
```

Am using the latest Carthage version 0.35.0, and set it in my Cartfile as `github "gilesvangruisen/Swift-YouTube-Player" == 0.7.1`

**Comment by gilesvangruisen** [comment]
@jianyaoang shoot, I think you're right! I just pushed 0.7.2, which hopefully has fixed the shared scheme issue. Please let me know if that works, thanks!
